### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by alifzl** [raghujhts13/text-to-sql#1]
Hi there,

Hope this issue finds you well :))

could you please add an instruction for how I should setup this code in my local machine.
I tried python 3.11 and 3.9 but resolving requirements.txt was not successful.

cheers.

**Comment by raghujhts13** [comment]
Hi @alifzl , please find below the versions used

- python==3.10.9
- ctransformers==0.2.24
- pygwalker==0.3.4
- pandas==2.0.3
- scipy==1.10.0
- sqlalchemy==1.4.39
- flask==2.2.2
- bitsandbytes==0.41.1

I will update the requirements.txt as well.
